// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description of Product 1",
                            Name = "Product 1",
                            Price = 590m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description of Product 2",
                            Name = "Product 2",
                            Price = 279m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description of Product 3",
                            Name = "Product 3",
                            Price = 395m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description of Product 4",
                            Name = "Product 4",
                            Price = 980m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description of Product 5",
                            Name = "Product 5",
                            Price = 479m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description of Product 6",
                            Name = "Product 6",
                            Price = 596m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description of Product 7",
                            Name = "Product 7",
                            Price = 367m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description of Product 8",
                            Name = "Product 8",
                            Price = 458m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description of Product 9",
                            Name = "Product 9",
                            Price = 851m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description of Product 10",
                            Name = "Product 10",
                            Price = 275m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description of Product 11",
                            Name = "Product 11",
                            Price = 734m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description of Product 12",
                            Name = "Product 12",
                            Price = 472m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description of Product 13",
                            Name = "Product 13",
                            Price = 216m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description of Product 14",
                            Name = "Product 14",
                            Price = 656m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description of Product 15",
                            Name = "Product 15",
                            Price = 123m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description of Product 16",
                            Name = "Product 16",
                            Price = 366m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description of Product 17",
                            Name = "Product 17",
                            Price = 732m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description of Product 18",
                            Name = "Product 18",
                            Price = 732m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description of Product 19",
                            Name = "Product 19",
                            Price = 612m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description of Product 20",
                            Name = "Product 20",
                            Price = 157m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description of Product 21",
                            Name = "Product 21",
                            Price = 159m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description of Product 22",
                            Name = "Product 22",
                            Price = 904m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description of Product 23",
                            Name = "Product 23",
                            Price = 554m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description of Product 24",
                            Name = "Product 24",
                            Price = 603m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description of Product 25",
                            Name = "Product 25",
                            Price = 755m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description of Product 26",
                            Name = "Product 26",
                            Price = 247m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description of Product 27",
                            Name = "Product 27",
                            Price = 811m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description of Product 28",
                            Name = "Product 28",
                            Price = 471m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description of Product 29",
                            Name = "Product 29",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description of Product 30",
                            Name = "Product 30",
                            Price = 201m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description of Product 31",
                            Name = "Product 31",
                            Price = 737m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description of Product 32",
                            Name = "Product 32",
                            Price = 644m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description of Product 33",
                            Name = "Product 33",
                            Price = 887m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description of Product 34",
                            Name = "Product 34",
                            Price = 610m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description of Product 35",
                            Name = "Product 35",
                            Price = 848m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description of Product 36",
                            Name = "Product 36",
                            Price = 195m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description of Product 37",
                            Name = "Product 37",
                            Price = 435m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description of Product 38",
                            Name = "Product 38",
                            Price = 714m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description of Product 39",
                            Name = "Product 39",
                            Price = 573m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description of Product 40",
                            Name = "Product 40",
                            Price = 967m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description of Product 41",
                            Name = "Product 41",
                            Price = 651m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description of Product 42",
                            Name = "Product 42",
                            Price = 712m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description of Product 43",
                            Name = "Product 43",
                            Price = 414m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description of Product 44",
                            Name = "Product 44",
                            Price = 626m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description of Product 45",
                            Name = "Product 45",
                            Price = 632m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description of Product 46",
                            Name = "Product 46",
                            Price = 345m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description of Product 47",
                            Name = "Product 47",
                            Price = 166m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description of Product 48",
                            Name = "Product 48",
                            Price = 507m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description of Product 49",
                            Name = "Product 49",
                            Price = 139m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description of Product 50",
                            Name = "Product 50",
                            Price = 721m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description of Product 51",
                            Name = "Product 51",
                            Price = 710m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description of Product 52",
                            Name = "Product 52",
                            Price = 789m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description of Product 53",
                            Name = "Product 53",
                            Price = 450m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description of Product 54",
                            Name = "Product 54",
                            Price = 676m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description of Product 55",
                            Name = "Product 55",
                            Price = 884m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description of Product 56",
                            Name = "Product 56",
                            Price = 686m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description of Product 57",
                            Name = "Product 57",
                            Price = 724m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description of Product 58",
                            Name = "Product 58",
                            Price = 792m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description of Product 59",
                            Name = "Product 59",
                            Price = 325m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description of Product 60",
                            Name = "Product 60",
                            Price = 331m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description of Product 61",
                            Name = "Product 61",
                            Price = 784m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description of Product 62",
                            Name = "Product 62",
                            Price = 895m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description of Product 63",
                            Name = "Product 63",
                            Price = 386m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description of Product 64",
                            Name = "Product 64",
                            Price = 750m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description of Product 65",
                            Name = "Product 65",
                            Price = 538m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description of Product 66",
                            Name = "Product 66",
                            Price = 190m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description of Product 67",
                            Name = "Product 67",
                            Price = 584m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description of Product 68",
                            Name = "Product 68",
                            Price = 605m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description of Product 69",
                            Name = "Product 69",
                            Price = 808m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description of Product 70",
                            Name = "Product 70",
                            Price = 927m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description of Product 71",
                            Name = "Product 71",
                            Price = 930m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description of Product 72",
                            Name = "Product 72",
                            Price = 117m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description of Product 73",
                            Name = "Product 73",
                            Price = 259m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description of Product 74",
                            Name = "Product 74",
                            Price = 644m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description of Product 75",
                            Name = "Product 75",
                            Price = 505m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description of Product 76",
                            Name = "Product 76",
                            Price = 447m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description of Product 77",
                            Name = "Product 77",
                            Price = 589m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description of Product 78",
                            Name = "Product 78",
                            Price = 928m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description of Product 79",
                            Name = "Product 79",
                            Price = 970m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description of Product 80",
                            Name = "Product 80",
                            Price = 509m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description of Product 81",
                            Name = "Product 81",
                            Price = 181m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description of Product 82",
                            Name = "Product 82",
                            Price = 404m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description of Product 83",
                            Name = "Product 83",
                            Price = 432m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description of Product 84",
                            Name = "Product 84",
                            Price = 449m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description of Product 85",
                            Name = "Product 85",
                            Price = 490m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description of Product 86",
                            Name = "Product 86",
                            Price = 947m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description of Product 87",
                            Name = "Product 87",
                            Price = 293m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description of Product 88",
                            Name = "Product 88",
                            Price = 310m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description of Product 89",
                            Name = "Product 89",
                            Price = 725m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description of Product 90",
                            Name = "Product 90",
                            Price = 261m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description of Product 91",
                            Name = "Product 91",
                            Price = 471m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description of Product 92",
                            Name = "Product 92",
                            Price = 643m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description of Product 93",
                            Name = "Product 93",
                            Price = 488m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description of Product 94",
                            Name = "Product 94",
                            Price = 341m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description of Product 95",
                            Name = "Product 95",
                            Price = 282m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description of Product 96",
                            Name = "Product 96",
                            Price = 755m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description of Product 97",
                            Name = "Product 97",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description of Product 98",
                            Name = "Product 98",
                            Price = 664m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description of Product 99",
                            Name = "Product 99",
                            Price = 188m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description of Product 100",
                            Name = "Product 100",
                            Price = 542m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 94
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 99
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 70
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 88
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 64
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
